### ISSUE TITLE
Development Tracker

### ISSUE THREAD

**Issue by LithyRiolu** [Lithe-Project/Stash-GUI#1]
[#1](https://github.com/Lithe-Project/Stash-GUI/issues/1) will be used to keep track of development and is to be updated with what needs to doing and what has been done so far. Because we forked TurtleCoin's Nest for this, I want to make sure everything works with TurtleCoin's RPC to its core daemons allowing people to use and then progress with making the GUI work for Monero forks.

[Known bugs are listed here.](https://github.com/Lithe-Project/Stash-GUI/blob/master/known-bugs.md)

###### Connection
- [x] connect with `turtle-service`
- [ ] connect with `TurtleCoind`
- [x] create wallet 
- [ ] import wallet
- [ ] open wallet
- [ ] use local blockchain
- [ ] use remote node
- [ ] use checkpoints

###### Display
- [x] wallet address 
- [ ] wallet keys
- [x] wallet filename
- [x] wallet balance
- [ ] wallet history
- [ ] network/node fee
- [ ] sync progress with progress bar

###### Transactions
- [ ] send transaction
- [ ] choose mixin - **(can't test with TRTL)**
- [ ] choose fee 
- [ ] send transaction with paymentID
- [ ] generate random a paymentID

###### Settings
- [x] close wallet (this closes the whole app)

###### Misc / Feature Requests
- [ ] Pool mining (probably with XMR-stak/XMRig)
- [ ] Solo mining
- [ ] dark/light mode

###### Monero's backend development will start once TurtleCoin's backend has been done.
